#-----------------------------------------------------------
# Image Setup
#-----------------------------------------------------------
#
# To edit the 'big-data-europe/docker-spark' base Image
# Github: https://github.com/big-data-europe/docker-spark
#
#

ARG SPARK_VERSION

FROM bde2020/spark-worker:${SPARK_VERSION}

LABEL maintainer="kangell <leikou@163.com>"
